### ISSUE TITLE
Provide an option to chomp the output(s)?

### ISSUE THREAD

**Issue by chocolateboy** [cargomedia/komenda#22]
First of all, thanks for this module! Ruby has a million different ways to do this and none of them have ever DWIM. Komenda has allowed me to jettison years of hacks, workarounds and FIXMEs :tada:

One thing I find myself doing when using this module is overriding the output methods (`stdout`, `stderr` and `output`) in Komenda::Result with chomping versions e.g.:

```ruby
module Komenda
  class Result
      def output
        @output[:combined].chomp
      end
  end
end
```

It would be great if there was a way for this to be enabled (or disabled) via an option e.g.:

```ruby
result = Komenda.run command, chomp: true
```

Which could possibly be shorthand for:

```ruby
result = Komenda.run command, chomp: { stdout: true, stderr: true, output: true }
```

**Comment by njam** [comment]
Glad to hear that it's useful!

A "chomp" option sounds reasonable. Probably the strings should be chomped in `process.rb`, before creating the `Result` instance, wdyt? Would you mind implementing the change?

**Comment by njam** [comment]
@chocolateboy I'm closing the ticket, as I don't have a need for this. But I would gladly accept a pull request!
